"""
MOM (Minutes of Meeting) HTML Generator.

Builds global and personalised MOM HTML strings. No external template engine —
built with Python f-strings for simplicity.
"""

from datetime import datetime


class MOMGenerator:
    """Generates HTML MOM documents."""

    def generate_global(
        self,
        summary: str,
        decisions: list[dict],
        topics: list[dict],
        action_items: list[dict],
        participants: list[dict] = None,
        session: dict = None,
        **kwargs,
    ) -> str:
        """
        Generate the global MOM HTML.

        Sections (in order):
        1. Header (title, date, duration, participants)
        2. Executive Summary
        3. Key Topics Discussed
        4. Decisions Made
        5. All Action Items (table)
        6. Unresolved Items
        7. Footer
        """
        participants = participants or []
        session = session or {}
        date_str = datetime.now().strftime("%B %d, %Y at %I:%M %p")

        participant_names = ", ".join(p.get("display_name", "Unknown") for p in participants) or "N/A"

        topics_html = "".join(
            f'<li><strong>{t.get("speaker", "")}</strong>: {t.get("text", "")}</li>'
            for t in topics
        ) or "<li>No specific topics recorded.</li>"

        decisions_html = "".join(
            f'<li><strong>{d.get("speaker", "")}</strong>: {d.get("text", "")}</li>'
            for d in decisions
        ) or "<li>No decisions recorded.</li>"

        # Action items table rows
        ai_rows = ""
        unresolved = []
        for ai in action_items:
            assignee = ai.get("assigned_to_name") or "Unassigned"
            if assignee == "Unassigned" or ai.get("assigned_to_name") is None:
                unresolved.append(ai)

            conf = ai.get("confidence", 0)
            conf_str = f"{conf:.0%}" if conf else "N/A"
            ai_rows += f"""
            <tr>
                <td>{ai.get('task_description', '')}</td>
                <td>{assignee}</td>
                <td>{ai.get('assigned_by_name', 'N/A')}</td>
                <td>{ai.get('deadline', 'N/A') or 'N/A'}</td>
                <td>{conf_str}</td>
            </tr>"""

        if not ai_rows:
            ai_rows = '<tr><td colspan="5" style="text-align:center;">No action items recorded.</td></tr>'

        unresolved_html = "".join(
            f'<li>{u.get("task_description", "")}</li>' for u in unresolved
        ) or "<li>None — all tasks are assigned.</li>"

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MeetMind — Minutes of Meeting</title>
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #1a1a1a; background: #fafafa; }}
    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 28px; border-radius: 12px; margin-bottom: 24px; }}
    .header h1 {{ margin: 0 0 8px 0; font-size: 24px; }}
    .header p {{ margin: 4px 0; opacity: 0.9; font-size: 14px; }}
    .section {{ background: white; padding: 20px; border-radius: 8px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
    .section h2 {{ color: #667eea; margin-top: 0; font-size: 18px; border-bottom: 2px solid #667eea; padding-bottom: 8px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th {{ background: #667eea; color: white; padding: 10px 12px; text-align: left; }}
    td {{ padding: 10px 12px; border-bottom: 1px solid #eee; }}
    tr:hover td {{ background: #f8f8ff; }}
    ul {{ padding-left: 20px; }}
    li {{ margin-bottom: 8px; line-height: 1.5; }}
    .footer {{ text-align: center; color: #888; font-size: 12px; padding: 16px; margin-top: 24px; }}
</style>
</head>
<body>

<div class="header">
    <h1>📋 Minutes of Meeting</h1>
    <p><strong>Date:</strong> {date_str}</p>
    <p><strong>Participants:</strong> {participant_names}</p>
    <p><strong>Generated by MeetMind AI</strong></p>
</div>

<div class="section">
    <h2>📝 Executive Summary</h2>
    <p>{summary}</p>
</div>

<div class="section">
    <h2>💬 Key Topics Discussed</h2>
    <ul>{topics_html}</ul>
</div>

<div class="section">
    <h2>✅ Decisions Made</h2>
    <ul>{decisions_html}</ul>
</div>

<div class="section">
    <h2>📌 Action Items</h2>
    <table>
        <thead>
            <tr><th>Task</th><th>Assigned To</th><th>Assigned By</th><th>Deadline</th><th>Confidence</th></tr>
        </thead>
        <tbody>{ai_rows}</tbody>
    </table>
</div>

<div class="section">
    <h2>⚠️ Unresolved Items</h2>
    <ul>{unresolved_html}</ul>
</div>

<div class="footer">
    <p>Generated by <strong>MeetMind</strong> — AI-Powered Meeting Assistant</p>
</div>

</body>
</html>"""

    def generate_personalised(
        self,
        participant: dict,
        summary: str,
        decisions: list[dict],
        topics: list[dict],
        tasks: list[dict],
        **kwargs,
    ) -> str:
        """
        Generate a personalised MOM for one participant.

        participant: { display_name, email }
        tasks: list of ActionItem dicts assigned to this participant only
        """
        first_name = participant.get("display_name", "there").split()[0]
        date_str = datetime.now().strftime("%B %d, %Y")

        decisions_html = "".join(
            f'<li><strong>{d.get("speaker", "")}</strong>: {d.get("text", "")}</li>'
            for d in decisions
        ) or "<li>No decisions recorded.</li>"

        tasks_html = ""
        for t in tasks:
            deadline = t.get("deadline")
            deadline_style = ""
            if deadline:
                deadline_str = f' <span style="{deadline_style}">📅 {deadline}</span>'
            else:
                deadline_str = ""
            tasks_html += f'<li>☐ {t.get("task_description", "")}{deadline_str}</li>'

        if not tasks_html:
            tasks_html = "<li>No action items assigned to you.</li>"

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MeetMind — Your Meeting Summary</title>
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 24px; color: #1a1a1a; background: #fafafa; }}
    .greeting {{ font-size: 20px; color: #333; margin-bottom: 20px; }}
    .section {{ background: white; padding: 20px; border-radius: 8px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
    .section h2 {{ color: #764ba2; margin-top: 0; font-size: 16px; border-bottom: 2px solid #764ba2; padding-bottom: 8px; }}
    ul {{ padding-left: 20px; }}
    li {{ margin-bottom: 10px; line-height: 1.5; }}
    .your-tasks {{ border-left: 4px solid #667eea; }}
    .footer {{ text-align: center; color: #888; font-size: 12px; padding: 16px; }}
</style>
</head>
<body>

<p class="greeting">Hi {first_name},</p>
<p>Here's your personalised summary from the meeting on <strong>{date_str}</strong>.</p>

<div class="section">
    <h2>📝 Meeting Summary</h2>
    <p>{summary}</p>
</div>

<div class="section">
    <h2>✅ Key Decisions</h2>
    <ul>{decisions_html}</ul>
</div>

<div class="section your-tasks">
    <h2>📌 YOUR Action Items</h2>
    <ul>{tasks_html}</ul>
</div>

<div class="footer">
    <p>Generated by <strong>MeetMind</strong> — AI-Powered Meeting Assistant</p>
</div>

</body>
</html>"""
